---
- name: Configure OpenSSH daemon
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config mode=0600 owner=root group=root validate="/usr/sbin/sshd -T -f %s"
  notify: Reload sshd

- name: Configure OpenSSH client
  template: src=ssh_config.j2 dest=/etc/ssh/ssh_config mode=0644 owner=root group=root

- name: Create SSH banner
  template: src=banner.txt dest=/etc/issue